#!/usr/bin/python
import atexit, errno, logging, os, select, signal
import sqlite3, subprocess, sys, time, traceback
from re6st import plib, utils, db, tunnel


def getConfig():
    parser = utils.ArgParser(fromfile_prefix_chars='@',
        description="Resilient virtual private network application.")
    _ = parser.add_argument

    _('--ip',
        help="IP address advertised to other nodes. Special values:\n"
             "- upnp: force autoconfiguration via UPnP\n"
             "- any: ask peers our IP\n"
             " (default: ask peers if UPnP fails)")
    _('--registry', metavar='URL',
        help="Public HTTP URL of the registry, for bootstrapping.")
    _('-l', '--log', default='/var/log/re6stnet',
        help="Path to the directory used for log files:\n"
             "- re6stnet.log: log file of re6stnet itself\n"
             "- babeld.log: log file of router\n"
             "- <iface>.log: 1 file per spawned OpenVPN\n")
    _('-s', '--state', default='/var/lib/re6stnet',
        help="Path to re6stnet state directory:\n"
             "- peers.db: cache of peer addresses\n"
             "- babeld.state: see option -S of babeld\n")
    _('-v', '--verbose', default=1, type=int, metavar='LEVEL',
        help="Log level of re6stnet itself. 0 disables logging."
             " Use SIGUSR1 to reopen log."
             " See also --babel-verb and --verb for logs of spawned processes.")
    _('-i', '--interface', action='append', dest='iface_list', default=[],
        help="Extra interface for LAN discovery. Highly recommanded if there"
             " are other re6st node on the same network segment.")
    _('-I', '--main-interface', metavar='IFACE', default='lo',
        help="Set re6stnet IP on given interface. Any interface not used for"
             " tunnelling can be chosen.")
    _('--up', metavar='CMD',
        help="Shell command to run after successful initialization.")

    _ = parser.add_argument_group('routing').add_argument
    _('-B', dest='babel_args', metavar='ARG', action='append', default=[],
        help="Extra arguments to forward to Babel.")
    _('--babel-pidfile', metavar='PID', default='/var/run/re6st-babeld.pid',
        help="Specify a file to write our process id to"
             " (option -I of Babel).")
    _('--hello', type=int, default=15,
        help="Hello interval in seconds, for both wired and wireless"
             " connections. OpenVPN ping-exit option is set to 4 times the"
             " hello interval. It takes between 3 and 4 times the"
             " hello interval for Babel to re-establish connection with a"
             " node for which the direct connection has been cut.")

    _ = parser.add_argument_group('tunnelling').add_argument
    _('-O', dest='openvpn_args', metavar='ARG', action='append', default=[],
        help="Extra arguments to forward to both server and client OpenVPN"
             " subprocesses. Often used to configure verbosity.")
    _('--ovpnlog', action='store_true',
        help="Tell each OpenVPN subprocess to log to a dedicated file.")
    _('--encrypt', action='store_true',
        help='Specify that tunnels should be encrypted.')
    _('--pp', nargs=2, action='append', metavar=('PORT', 'PROTO'),
        help="Port and protocol to be announced to other peers, ordered by"
             " preference. For each protocol (either udp or tcp), start one"
             " openvpn server on the first given port."
             " (default: --pp 1194 udp --pp 1194 tcp)")
    _('--dh',
        help='File containing Diffie-Hellman parameters in .pem format')
    _('--ca', required=True, help=parser._ca_help)
    _('--cert', required=True,
        help="Local peer's signed certificate in .pem format."
             " Common name defines the allocated prefix in the network.")
    _('--key', required=True,
        help="Local peer's private key in .pem format.")
    _('--client-count', default=10, type=int,
        help="Number of client tunnels to set up.")
    _('--max-clients', type=int,
        help="Maximum number of accepted clients per OpenVPN server. (default:"
             " client-count * 2, which actually represents the average number"
             " of tunnels to other peers)")
    _('--tunnel-refresh', default=300, type=int,
        help="Interval in seconds between two tunnel refresh: the worst"
             " tunnel is closed if the number of client tunnels has reached"
             " its maximum number (client-count).")
    _('--client', metavar='HOST,PORT,PROTO[;...]',
        help="Do not run any OpenVPN server, but only 1 OpenVPN client,"
             " with specified remotes. Any other option not required in this"
             " mode is ignored (e.g. client-count, max-clients, etc.)")

    return parser.parse_args()


def main():
    # Get arguments
    config = getConfig()
    network = utils.networkFromCa(config.ca)
    prefix = utils.binFromSubnet(utils.subnetFromCert(config.cert))
    config.openvpn_args += (
        '--ca', config.ca,
        '--cert', config.cert,
        '--key', config.key)
    # TODO: verify certificates (should we moved to M2Crypto ?)

    # Set logging
    utils.setupLog(config.verbose, os.path.join(config.log, 're6stnet.log'))

    logging.trace("Configuration:\n%r", config)
    utils.makedirs(config.state)
    db_path = os.path.join(config.state, 'peers.db')
    if config.ovpnlog:
        plib.ovpn_log = config.log

    signal.signal(signal.SIGHUP, lambda *args: sys.exit(-1))
    signal.signal(signal.SIGTERM, lambda *args: sys.exit())

    if config.max_clients is None:
        config.max_clients = config.client_count * 2

    address = []
    server_tunnels = {}
    if config.client:
        config.babel_args.append('re6stnet')
    elif config.max_clients:
        if config.pp:
            pp = [(int(port), proto) for port, proto in config.pp]
        else:
            pp = (1194, 'udp'), (1194, 'tcp')
        ip_changed = lambda ip: [(ip, str(port), proto) for port, proto in pp]
        forwarder = None
        if config.ip == 'upnp' or not config.ip:
            logging.info('Attempting automatic configuration via UPnP...')
            try:
                from re6st.upnpigd import Forwarder
                forwarder = Forwarder()
            except Exception, e:
                if config.ip:
                    raise
                logging.info("%s: assume we are not NATed", e)
            else:
                atexit.register(forwarder.clear)
                for port, proto in pp:
                    ip, port = forwarder.addRule(port, proto)
                    address.append((ip, str(port), proto))
        elif config.ip != 'any':
            address = ip_changed(config.ip)
        if address:
            ip_changed = None
        for x in pp:
            server_tunnels.setdefault('re6stnet-' + x[1], x)

    def required(arg):
        if not getattr(config, arg):
            sys.exit("error: argument --%s is required" % arg)
    def ip(object, *args):
        args = ['ip', object, 'add'] + list(args)
        r = subprocess.call(args)
        if r:
            sys.exit(r)
        args[2] = 'del'
        cleanup.append(lambda: subprocess.call(args))

    try:
        subnet = network + prefix
        my_ip = '%s/%s' % (utils.ipFromBin(subnet, '1'), len(subnet))

        # Init db and tunnels
        tunnel_interfaces = server_tunnels.keys()
        timeout = 4 * config.hello
        if config.client_count and not config.client:
            required('registry')
            # Create and open read_only pipe to get server events
            r_pipe, write_pipe = os.pipe()
            read_pipe = os.fdopen(r_pipe)
            peer_db = db.PeerDB(db_path, config.registry, config.key, prefix)
            tunnel_manager = tunnel.TunnelManager(write_pipe, peer_db,
                config.openvpn_args, timeout, config.tunnel_refresh,
                config.client_count, config.iface_list, network, prefix,
                address, ip_changed, config.encrypt)
            tunnel_interfaces += tunnel_manager.free_interface_set
        else:
            tunnel_manager = write_pipe = None

        config.babel_args += config.iface_list
        cleanup = [plib.router(network, subnet, config.hello,
            os.path.join(config.log, 'babeld.log'),
            os.path.join(config.state, 'babeld.state'),
            config.babel_pidfile, tunnel_interfaces,
            *config.babel_args).terminate]

        try:
            my_network = "%s/%u" % (utils.ipFromBin(network), len(network))
            ip('route', 'unreachable', my_network, 'proto', 'static')
            # Source address selection is defined by RFC 3484, and in most
            # applications, it usually works  thanks to rule 5 (prefer outgoing
            # interface). But here, it rarely applies because we use several
            # interfaces to connect to a re6st network.
            # Rule 7 is little strange because it prefers temporary addresses
            # over IP with a longer matching prefix (rule 8, which is not even
            # mandatory).
            # So only rule 6 can make the difference, i.e. prefer same label.
            # The value of the label does not matter, except that it must be
            # different from ::/0's (normally equal to 1).
            # XXX: This does not work with extra interfaces that already have
            #      an public IP so Babel must be changed to set a source
            #      address on routes it installs.
            ip('addrlabel', 'prefix', my_network, 'label', '99')
            # prepare persistent interfaces
            if config.client:
                cleanup.append(plib.client('re6stnet', config.client,
                    config.encrypt, '--ping-restart', str(timeout),
                    *config.openvpn_args).kill)
            elif server_tunnels:
                required('dh')
                for iface, (port, proto) in server_tunnels.iteritems():
                    cleanup.append(plib.server(iface, config.max_clients,
                        config.dh, write_pipe, port, proto, config.encrypt,
                        '--ping-exit', str(timeout), *config.openvpn_args).kill)

            ip('addr', my_ip, 'dev', config.main_interface)
            if config.main_interface == 'lo':
                # WKRD: The kernel does not remove these routes on exit.
                #       The first one can be removed now.
                del_rtr = ['ip', 'route', 'del', 'unreachable', 'fe80::/64',
                           'dev', 'lo']
                subprocess.call(del_rtr)
                del_rtr[4] = '%s/%u' % (utils.ipFromBin(subnet), len(subnet))
                cleanup.append(lambda: subprocess.call(del_rtr))
            if config.up:
                r = os.system(config.up)
                if r:
                    sys.exit(r)

            # main loop
            if tunnel_manager is None:
                sys.exit(os.WEXITSTATUS(os.wait()[1]))
            cleanup.append(tunnel_manager.killAll)
            while True:
                next = tunnel_manager.next_refresh
                if forwarder:
                    next = min(next, forwarder.next_refresh)
                r = [read_pipe, tunnel_manager.sock]
                try:
                    r = select.select(r, [], [], max(0, next - time.time()))[0]
                except select.error as e:
                    if e.args[0] != errno.EINTR:
                        raise
                    continue
                if read_pipe in r:
                    tunnel_manager.handleTunnelEvent(read_pipe.readline())
                if tunnel_manager.sock in r:
                    tunnel_manager.handlePeerEvent()
                t = time.time()
                if t >= tunnel_manager.next_refresh:
                    tunnel_manager.refresh()
                if forwarder and t >= forwarder.next_refresh:
                    forwarder.refresh()
        finally:
            for cleanup in cleanup:
                try:
                    cleanup()
                except:
                    pass
    except sqlite3.Error:
        logging.exception("Restarting with empty cache")
        os.rename(db_path, db_path + '.bak')
        try:
            sys.exitfunc()
        finally:
            os.execvp(sys.argv[0], sys.argv)
    except KeyboardInterrupt:
        return 0
    except Exception:
        f = traceback.format_exception(*sys.exc_info())
        logging.error('%s%s', f.pop(), ''.join(f))
        sys.exit(1)

if __name__ == "__main__":
    main()
