#!/usr/bin/env python
def __file__():
    import argparse, os, sys
    sys.dont_write_bytecode = True
    sys.path[0] = os.path.dirname(sys.path[0])
    from argparse import ArgumentParser
    _parse_args = ArgumentParser.parse_args
    ArgumentParser.parse_args = lambda self: _parse_args(self, sys.argv[2:])

    return os.path.join(sys.path[0], sys.argv[1])
__file__ = __file__()
execfile(__file__)
